spring.application.name=tarefas-api

# Banco H2 em memória (para começar). Depois dá para trocar por PostgreSQL.
spring.datasource.url=jdbc:h2:mem:tarefasdb
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
